DROP TABLE IF EXISTS replacement_requests_archive CASCADE;
DROP TABLE IF EXISTS replacement_requests CASCADE;
DROP TABLE IF EXISTS timetable CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP SCHEMA IF EXISTS api CASCADE;
DROP TABLE IF EXISTS teacher_competencies CASCADE;
CREATE SCHEMA api;
CREATE TABLE teachers (name TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, phone TEXT NOT NULL, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE timetable (id SERIAL PRIMARY KEY, subject TEXT NOT NULL, classes INTEGER NOT NULL, dinner TEXT, team TEXT NOT NULL, teacher TEXT NOT NULL, date DATE NOT NULL, day_of_week INTEGER NOT NULL, week_num INTEGER NOT NULL, num_den TEXT NOT NULL, audiense TEXT, type TEXT, is_replacement BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE replacement_requests (id SERIAL PRIMARY KEY, teacher_name TEXT NOT NULL, request_date DATE NOT NULL, week_num INTEGER NOT NULL, num_den TEXT, classes INTEGER NOT NULL, subject TEXT NOT NULL, team TEXT NOT NULL, status TEXT DEFAULT 'pending', replacing_teacher TEXT, admin_comment TEXT, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE replacement_requests_archive (id INTEGER PRIMARY KEY, teacher_name TEXT NOT NULL, request_date DATE NOT NULL, week_num INTEGER NOT NULL, num_den TEXT, classes INTEGER NOT NULL, subject TEXT NOT NULL, team TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'confirmed', replacing_teacher TEXT, admin_comment TEXT, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, archived_at TIMESTAMP DEFAULT NOW());
CREATE TABLE api.users (email TEXT PRIMARY KEY, password_hash TEXT NOT NULL, role TEXT NOT NULL, teacher_name TEXT, created_at TIMESTAMP DEFAULT NOW());

-- Преподаватели 
INSERT INTO teachers (name, email, phone) VALUES ('Милехина Е. Н.', 'milehina@university.ru', '+7 (999) 222-22-22');
INSERT INTO teachers (name, email, phone) VALUES ('Захарова Ю. В.', 'zaharova@university.ru', '+7 (999) 333-33-33');
INSERT INTO teachers (name, email, phone) VALUES ('Зубарев К. М.', 'zubarev@university.ru', '+7 (999) 444-44-44');
INSERT INTO teachers (name, email, phone) VALUES ('Облакова Т. В.', 'oblakova@university.ru', '+7 (999) 555-55-55');
INSERT INTO teachers (name, email, phone) VALUES ('Скуднева О. В.', 'skudneva@university.ru', '+7 (999) 666-66-66');
INSERT INTO teachers (name, email, phone) VALUES ('Никулкин С. А.', 'nikulkin@university.ru', '+7 (999) 777-77-77');
INSERT INTO teachers (name, email, phone) VALUES ('Администратор', 'admin@university.ru', '+7 (999) 111-11-11');

INSERT INTO teachers (name, email, phone) VALUES ('Алгазин О. Д.', 'algazin@university.ru', '+7 (999) 101-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Анисова Т. Л.', 'anisova@university.ru', '+7 (999) 102-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Анохин Д. С.', 'anokhin@university.ru', '+7 (999) 103-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Аскеров Р. С.', 'askerov@university.ru', '+7 (999) 104-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Бебенина А. А.', 'bebenina@university.ru', '+7 (999) 105-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Белотелов Н. В.', 'belotelov@university.ru', '+7 (999) 106-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Белоконь А. И.', 'belokon@university.ru', '+7 (999) 107-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Богданов И. О.', 'bogdanov@university.ru', '+7 (999) 108-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Богод Д. А.', 'bogod@university.ru', '+7 (999) 109-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Бойко С. В.', 'boyko@university.ru', '+7 (999) 110-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Борович Г. К.', 'borovich@university.ru', '+7 (999) 111-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Бочкова Т. А.', 'bochkova@university.ru', '+7 (999) 112-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Валишин А. А.', 'valishin@university.ru', '+7 (999) 113-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Глотов А. А.', 'glotov@university.ru', '+7 (999) 114-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Гумиргалиев Т. Р.', 'gumirgaliev@university.ru', '+7 (999) 115-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Давыдов К. Э.', 'davydov@university.ru', '+7 (999) 116-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Демин А. И.', 'demin@university.ru', '+7 (999) 117-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Дерябина Г. С.', 'deryabina@university.ru', '+7 (999) 118-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Димитриенко Ю. И.', 'dimitrienko@university.ru', '+7 (999) 119-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Дробот Д. С.', 'drobo@university.ru', '+7 (999) 120-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Жидков Е. Н.', 'zhidkov@university.ru', '+7 (999) 121-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Захаров А. А.', 'zaharov@university.ru', '+7 (999) 122-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Громов С. А.', 'gromov@university.ru', '+7 (999) 124-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Иванов М. Ю.', 'ivanov@university.ru', '+7 (999) 125-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Каменев И. Г.', 'kamenev@university.ru', '+7 (999) 126-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Зямалов В. Е.', 'zyamalov@university.ru', '+7 (999) 127-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Иванова Т. Л.', 'ivanova@university.ru', '+7 (999) 128-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Каменских Г. М.', 'kamenskih@university.ru', '+7 (999) 129-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Каримов С. Б.', 'karimov@university.ru', '+7 (999) 130-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Киреева Е. А.', 'kireeva@university.ru', '+7 (999) 131-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Кирсанова Н. А.', 'kirsanova@university.ru', '+7 (999) 132-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Киселев В. В.', 'kiselev@university.ru', '+7 (999) 133-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Коновалов Ю. В.', 'konovalov@university.ru', '+7 (999) 134-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Краснов Г. А.', 'krasnov@university.ru', '+7 (999) 135-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Крылова А. Е.', 'krylova@university.ru', '+7 (999) 136-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Кудрявцева С. С.', 'kudryavceva@university.ru', '+7 (999) 137-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Кутыркин В. А.', 'kutyirkin@university.ru', '+7 (999) 138-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Лебедев С. В.', 'lebedev@university.ru', '+7 (999) 139-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Левина А. И.', 'levina@university.ru', '+7 (999) 140-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Лобков Д. С.', 'lobkov@university.ru', '+7 (999) 141-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Максименко Д. М.', 'maksimenko@university.ru', '+7 (999) 142-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Медведева Ю. А.', 'medvedeva@university.ru', '+7 (999) 143-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Мозжорина Т. Ю.', 'mozzhorina@university.ru', '+7 (999) 144-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Облаков А. И.', 'oblokov@university.ru', '+7 (999) 145-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Осипов Е. В.', 'osipov@university.ru', '+7 (999) 146-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Пархоменко В. П.', 'parhomenko@university.ru', '+7 (999) 147-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Покровский И. Л.', 'pokrovskiy@university.ru', '+7 (999) 148-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Полехина Г. Е.', 'polehina@university.ru', '+7 (999) 149-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Прозоровский А. А.', 'prozorovskiy@university.ru', '+7 (999) 150-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Рымкулов Д. Р.', 'rymkulov@university.ru', '+7 (999) 151-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Сергеева Е. С.', 'sergeeva@university.ru', '+7 (999) 152-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Смехнова А. А.', 'smekhnova@university.ru', '+7 (999) 153-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Смирнов В. М.', 'smirnov@university.ru', '+7 (999) 154-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Соболев А. В.', 'sobolev@university.ru', '+7 (999) 155-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Степанов В. А.', 'stepanov@university.ru', '+7 (999) 156-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Степанова Х. С.', 'stepanova@university.ru', '+7 (999) 157-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Чибисова А. В.', 'chibisova@university.ru', '+7 (999) 158-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Чупров П. А.', 'chuprov@university.ru', '+7 (999) 159-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Шапошников Д. А.', 'shaposhnikov@university.ru', '+7 (999) 160-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Шершакова А. О.', 'shershakova@university.ru', '+7 (999) 161-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Яковлев Д. О.', 'yakovlev@university.ru', '+7 (999) 162-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Яхновский А. Д.', 'yakhnovskiy@university.ru', '+7 (999) 163-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Тиняев С. В.', 'tinyaev@university.ru', '+7 (999) 164-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Титов Д. А.', 'titov@university.ru', '+7 (999) 165-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Тришина Е. А.', 'trishina@university.ru', '+7 (999) 166-10-10');
INSERT INTO teachers (name, email, phone) VALUES ('Тришин А. В.', 'trishin@university.ru', '+7 (999) 167-10-10');

-- Пользователи (все преподаватели + администратор, пароли из .env)
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('milehina@university.ru', 'env-managed', 'teacher', 'Милехина Е. Н.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('zaharova@university.ru', 'env-managed', 'teacher', 'Захарова Ю. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('zubarev@university.ru', 'env-managed', 'teacher', 'Зубарев К. М.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('oblakova@university.ru', 'env-managed', 'teacher', 'Облакова Т. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('skudneva@university.ru', 'env-managed', 'teacher', 'Скуднева О. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('nikulkin@university.ru', 'env-managed', 'teacher', 'Никулкин С. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('admin@university.ru', 'env-managed', 'admin', 'Администратор');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('algazin@university.ru', 'env-managed', 'teacher', 'Алгазин О. Д.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('anisova@university.ru', 'env-managed', 'teacher', 'Анисова Т. Л.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('anokhin@university.ru', 'env-managed', 'teacher', 'Анохин Д. С.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('askerov@university.ru', 'env-managed', 'teacher', 'Аскеров Р. С.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('bebenina@university.ru', 'env-managed', 'teacher', 'Бебенина А. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('belotelov@university.ru', 'env-managed', 'teacher', 'Белотелов Н. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('belokon@university.ru', 'env-managed', 'teacher', 'Белоконь А. И.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('bogdanov@university.ru', 'env-managed', 'teacher', 'Богданов И. О.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('bogod@university.ru', 'env-managed', 'teacher', 'Богод Д. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('boyko@university.ru', 'env-managed', 'teacher', 'Бойко С. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('borovich@university.ru', 'env-managed', 'teacher', 'Борович Г. К.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('bochkova@university.ru', 'env-managed', 'teacher', 'Бочкова Т. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('valishin@university.ru', 'env-managed', 'teacher', 'Валишин А. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('glotov@university.ru', 'env-managed', 'teacher', 'Глотов А. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('gumirgaliev@university.ru', 'env-managed', 'teacher', 'Гумиргалиев Т. Р.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('davydov@university.ru', 'env-managed', 'teacher', 'Давыдов К. Э.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('demin@university.ru', 'env-managed', 'teacher', 'Демин А. И.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('deryabina@university.ru', 'env-managed', 'teacher', 'Дерябина Г. С.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('dimitrienko@university.ru', 'env-managed', 'teacher', 'Димитриенко Ю. И.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('drobo@university.ru', 'env-managed', 'teacher', 'Дробот Д. С.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('zhidkov@university.ru', 'env-managed', 'teacher', 'Жидков Е. Н.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('zaharov@university.ru', 'env-managed', 'teacher', 'Захаров А. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('gromov@university.ru', 'env-managed', 'teacher', 'Громов С. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('ivanov@university.ru', 'env-managed', 'teacher', 'Иванов М. Ю.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('kamenev@university.ru', 'env-managed', 'teacher', 'Каменев И. Г.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('zyamalov@university.ru', 'env-managed', 'teacher', 'Зямалов В. Е.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('ivanova@university.ru', 'env-managed', 'teacher', 'Иванова Т. Л.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('kamenskih@university.ru', 'env-managed', 'teacher', 'Каменских Г. М.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('karimov@university.ru', 'env-managed', 'teacher', 'Каримов С. Б.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('kireeva@university.ru', 'env-managed', 'teacher', 'Киреева Е. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('kirsanova@university.ru', 'env-managed', 'teacher', 'Кирсанова Н. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('kiselev@university.ru', 'env-managed', 'teacher', 'Киселев В. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('konovalov@university.ru', 'env-managed', 'teacher', 'Коновалов Ю. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('krasnov@university.ru', 'env-managed', 'teacher', 'Краснов Г. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('krylova@university.ru', 'env-managed', 'teacher', 'Крылова А. Е.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('kudryavceva@university.ru', 'env-managed', 'teacher', 'Кудрявцева С. С.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('kutyirkin@university.ru', 'env-managed', 'teacher', 'Кутыркин В. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('lebedev@university.ru', 'env-managed', 'teacher', 'Лебедев С. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('levina@university.ru', 'env-managed', 'teacher', 'Левина А. И.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('lobkov@university.ru', 'env-managed', 'teacher', 'Лобков Д. С.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('maksimenko@university.ru', 'env-managed', 'teacher', 'Максименко Д. М.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('medvedeva@university.ru', 'env-managed', 'teacher', 'Медведева Ю. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('mozzhorina@university.ru', 'env-managed', 'teacher', 'Мозжорина Т. Ю.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('oblokov@university.ru', 'env-managed', 'teacher', 'Облаков А. И.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('osipov@university.ru', 'env-managed', 'teacher', 'Осипов Е. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('parhomenko@university.ru', 'env-managed', 'teacher', 'Пархоменко В. П.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('pokrovskiy@university.ru', 'env-managed', 'teacher', 'Покровский И. Л.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('polehina@university.ru', 'env-managed', 'teacher', 'Полехина Г. Е.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('prozorovskiy@university.ru', 'env-managed', 'teacher', 'Прозоровский А. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('rymkulov@university.ru', 'env-managed', 'teacher', 'Рымкулов Д. Р.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('sergeeva@university.ru', 'env-managed', 'teacher', 'Сергеева Е. С.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('smekhnova@university.ru', 'env-managed', 'teacher', 'Смехнова А. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('smirnov@university.ru', 'env-managed', 'teacher', 'Смирнов В. М.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('sobolev@university.ru', 'env-managed', 'teacher', 'Соболев А. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('stepanov@university.ru', 'env-managed', 'teacher', 'Степанов В. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('stepanova@university.ru', 'env-managed', 'teacher', 'Степанова Х. С.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('chibisova@university.ru', 'env-managed', 'teacher', 'Чибисова А. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('chuprov@university.ru', 'env-managed', 'teacher', 'Чупров П. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('shaposhnikov@university.ru', 'env-managed', 'teacher', 'Шапошников Д. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('shershakova@university.ru', 'env-managed', 'teacher', 'Шершакова А. О.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('yakovlev@university.ru', 'env-managed', 'teacher', 'Яковлев Д. О.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('yakhnovskiy@university.ru', 'env-managed', 'teacher', 'Яхновский А. Д.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('tinyaev@university.ru', 'env-managed', 'teacher', 'Тиняев С. В.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('titov@university.ru', 'env-managed', 'teacher', 'Титов Д. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('trishina@university.ru', 'env-managed', 'teacher', 'Тришина Е. А.');
INSERT INTO api.users (email, password_hash, role, teacher_name) VALUES ('trishin@university.ru', 'env-managed', 'teacher', 'Тришин А. В.');

-- Расписание загружается из data/schedule.csv (npm run import-schedule)
-- Компетенция рассчитывается в competency.js по данным timetable

-- Заявки
INSERT INTO replacement_requests (teacher_name, request_date, week_num, num_den, classes, subject, team, status, replacing_teacher) VALUES ('Милехина', '2026-04-27', 17, 'num', 2, 'Математический анализ', 'ФН11-33Б', 'pending', NULL);
INSERT INTO replacement_requests (teacher_name, request_date, week_num, num_den, classes, subject, team, status, replacing_teacher) VALUES ('Милехина', '2026-04-29', 17, 'num', 2, 'Математический анализ', 'ФН11-33Б', 'pending', NULL);
INSERT INTO replacement_requests (teacher_name, request_date, week_num, num_den, classes, subject, team, status, replacing_teacher) VALUES ('Зубарев', '2026-05-07', 18, 'den', 4, 'Программирование', 'ФН11-33Б', 'confirmed', 'Щетинин');

-- Индексы
CREATE INDEX idx_timetable_teacher ON timetable(teacher);
CREATE INDEX idx_timetable_date ON timetable(date);
CREATE INDEX idx_timetable_teacher_date ON timetable(teacher, date);
CREATE INDEX idx_timetable_subject_type ON timetable(subject, type);
CREATE INDEX idx_users_email ON api.users(email);
